import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('multiplayer Postgres rules protect and synchronize the complete room lifecycle', async t => {
  const db = new PGlite();
  t.after(()=>db.close());
  const ids = Array.from({length:10},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
  await db.exec(`create role anon; create role authenticated; create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
  for (const id of ids) await db.query('insert into auth.users values ($1)',[id]);
  const sql=await readFile(new URL('../multiplayer.sql',import.meta.url),'utf8');
  await db.exec(sql);
  await db.exec(sql); // Safe to apply again during setup.
  async function rpc(id,action,code='',payload={}) {
    return db.transaction(async tx=>{
      await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[id||'']);
      await tx.exec('set local role authenticated');
      return (await tx.query('select public.typequest_multiplayer($1,$2,$3::jsonb) as room',[action,code,JSON.stringify(payload)])).rows[0].room;
    });
  }
  const rejects=(promise,pattern)=>assert.rejects(promise,pattern);
  await rejects(rpc(null,'create'),/sign in/);
  await rejects(rpc(ids[0],'create','',{duration:1}),/check constraint/);
  let room=await rpc(ids[0],'create','',{name:'Host',duration:30,difficulty:'easy'});
  const code=room.code;
  assert.match(code,/^[A-F0-9]{8}$/);
  assert.equal((await rpc(ids[0],'create')).code,code,'create retry is idempotent');
  await rejects(rpc(ids[1],'sync',code),/Join this room/);
  await rejects(rpc(ids[1],'join','ZZZZZZZZ'),/8-character/);
  await rejects(rpc(ids[1],'join','00000000'),/not found/);
  room=await rpc(ids[1],'join',code.toLowerCase(),{name:'Friend'});
  assert.equal(room.players.length,2);
  await rejects(rpc(ids[1],'start',code),/Only the host/);
  await rejects(rpc(ids[0],'start',code),/ready/);
  for(let i=0;i<2;i++) await rpc(ids[i],'ready',code,{ready:true});
  room=await rpc(ids[0],'start',code);
  assert.equal(room.phase,'racing');
  assert.ok(Date.parse(room.startsAt)>Date.parse(room.serverNow));
  assert.equal((await rpc(ids[0],'start',code)).startsAt,room.startsAt,'duplicate start never restarts clock');
  await rejects(rpc(ids[2],'join',code),/already started/);
  let progress={round:1,sequence:1,typed:'the',attempts:3,errors:0};
  assert.equal((await rpc(ids[0],'sync',code,progress)).players.find(p=>p.id===ids[0]).correct,0,'countdown blocks typing');
  await db.query("update typequest_private.rooms set starts_at=clock_timestamp()-interval '2 seconds' where code=$1",[code]);
  room=await rpc(ids[0],'sync',code,progress);
  assert.equal(room.players.find(p=>p.id===ids[0]).correct,3);
  assert.equal(room.myText,'the','refresh can restore accepted text');
  progress={...progress,sequence:2,typed:'the X',attempts:5,errors:1};
  room=await rpc(ids[0],'sync',code,progress);
  assert.equal(room.players.find(p=>p.id===ids[0]).accuracy,80);
  progress={...progress,sequence:3,typed:'the s',attempts:6};
  room=await rpc(ids[0],'sync',code,progress);
  assert.equal(room.players.find(p=>p.id===ids[0]).correct,5);
  assert.equal(room.players.find(p=>p.id===ids[0]).errors,1,'correction cannot erase a mistake');
  room=await rpc(ids[0],'sync',code,{...progress,sequence:2,typed:'bad'});
  assert.equal(room.myText,'the s','stale packets cannot overwrite progress');
  await rejects(rpc(ids[0],'sync',code,{...progress,sequence:4,errors:0}),/Invalid typing/);
  await rejects(rpc(ids[0],'sync',code,{...progress,sequence:4,attempts:9999}),/Invalid typing/);
  await rejects(rpc(ids[0],'sync',code,{round:1,sequence:4,typed:'cheat'}),/Invalid typing/);
  await rejects(rpc(ids[0],'sync',code,{...progress,round:2,sequence:4}),/round has ended/);
  await db.query("update typequest_private.rooms set starts_at=clock_timestamp()-interval '31 seconds' where code=$1",[code]);
  room=await rpc(ids[0],'sync',code,{...progress,sequence:4,typed:'the sun',attempts:8});
  assert.equal(room.phase,'results'); assert.equal(room.myText,'the s','no scores accepted after the deadline');
  assert.equal(room.players.find(p=>p.id===ids[0]).wpm,2,'WPM uses the full server duration');
  await rejects(rpc(ids[1],'rematch',code),/Only the host/);
  room=await rpc(ids[0],'rematch',code);
  assert.equal(room.round,2); assert.equal(room.phase,'lobby'); assert.equal(room.myText,'');
  assert.ok(room.players.every(p=>!p.ready&&p.correct===0&&p.sequence===0));
  for(let i=2;i<8;i++) await rpc(ids[i],'join',code,{name:`Player ${i}`});
  await rejects(rpc(ids[8],'join',code),/full/);
  await rpc(ids[7],'leave',code);
  room=await rpc(ids[8],'join',code); assert.equal(room.players.length,8);
  await rpc(ids[0],'leave',code);
  room=await rpc(ids[1],'sync',code); assert.notEqual(room.hostId,ids[0],'host transfers on leaving');
  await db.query("update typequest_private.players set last_seen=clock_timestamp()-interval '40 seconds' where code=$1 and user_id<>$2",[code,ids[1]]);
  room=await rpc(ids[1],'sync',code); assert.equal(room.hostId,ids[1]); assert.equal(room.players.length,1,'stale lobby players are removed');
  await rejects(rpc(ids[1],'start',code),/two players/);
  await rejects(db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query('select * from typequest_private.players');}),/permission denied/);
  await rejects(db.transaction(async tx=>{await tx.exec('set local role anon');await tx.query("select public.typequest_multiplayer('create')");}),/permission denied/);
  const exposed=(await db.query("select prosecdef from pg_proc where proname='typequest_multiplayer'")).rows[0];
  assert.equal(exposed.prosecdef,false,'exposed wrapper must use invoker privileges');
  await db.query("update typequest_private.rooms set expires_at=clock_timestamp()-interval '1 second' where code=$1",[code]);
  await rejects(rpc(ids[1],'sync',code),/expired/);
});
