import React, { useState } from 'react';
import { LEVELS } from '../data/levels';
import { ZONES, makePlan } from '../lib/coach';

export function Landscape() {
  return <svg className="questLandscape" viewBox="0 0 600 360" aria-hidden="true"><defs><linearGradient id="questSky" x2="0" y2="1"><stop stopColor="#303c5f"/><stop offset="1" stopColor="#172d38"/></linearGradient></defs><rect width="600" height="360" rx="30" fill="url(#questSky)"/><circle cx="445" cy="95" r="44" fill="#f6df9f"/><g fill="#b7dbd0"><circle cx="110" cy="53" r="2"/><circle cx="288" cy="41" r="2"/><circle cx="540" cy="64" r="2"/></g><path d="M0 245 133 100 244 248 371 130 600 274V360H0Z" fill="#355065"/><path d="m87 151 46-51 48 64-43-15-15 15Z" fill="#a8c3c9"/><path d="M0 278 123 236 262 293 395 213 600 258V360H0Z" fill="#346756"/><path d="M0 319Q145 250 280 322T600 301V360H0Z" fill="#204c41"/><path d="M280 360Q465 310 364 280T390 238" fill="none" stroke="#d5c295" strokeWidth="16"/><g fill="#133e34">{[30,75,180,480,535,575].map((x,i)=><path key={x} d={`M${x} ${210+i%2*30}l-25 65h16v30h18v-30h16Z`}/>)}</g><path d="M390 242v-57l40 13-40 15" fill="#ffc774" stroke="#ffc774" strokeWidth="4"/><circle cx="323" cy="316" r="10" fill="#b6f28a" stroke="#fff" strokeWidth="3"/></svg>;
}

export function AdventureHome({ data, onStart, onMap, onCoach, onTheme }) {
  const level = LEVELS[Math.min(50,data.currentLevel)-1];
  const zone = ZONES[Math.floor((level.id-1)/10)];
  const count = Object.keys(data.completed).length;
  const plan = makePlan(data,level);
  const goal = data.settings.dailyGoal || 10;
  const minutes = Math.round((data.dailyMinutes?.[plan.day] || 0)*10)/10;
  return <div className="adventureHome">
    <div className="questHeading"><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>A little practice.<br/><em>A new superpower.</em></h1></div><span className="rankPill">{zone.icon} {count >= 50 ? 'Grandmaster' : count >= 30 ? 'Pathfinder' : count >= 10 ? 'Explorer' : 'Rookie'}</span></div>
    <section className="expeditionHero"><div className="expeditionCopy"><span className="questTag">WORLD {Math.floor((level.id-1)/10)+1} / 5 · {zone.name}</span><h2>{level.title}</h2><p>One level closer to effortless typing. Your next adventure starts with a single key.</p><div className="questSpecs"><span>◈ Level {level.id}</span><span>↗ {level.targetWpm} WPM</span><span>◎ {level.minAccuracy}% accuracy</span></div><button className="primary questPrimary" onClick={()=>onStart(level.id)}>Continue journey <span>↗</span></button></div><Landscape/></section>
    <div className="questNumbers">{[[`${count}/50`,'LEVELS CLEARED','◈'],[`${data.totalStars}/150`,'STARS EARNED','✦'],[data.bestWpm || '—','BEST WPM','↗'],[`${data.streak} days`,'CURRENT STREAK','ϟ']].map(([value,label,icon])=><div key={label}><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>)}</div>
    <div className="questColumns"><section className="questPanel worldPreview"><div className="questSectionTitle"><div><p className="eyebrow">THE BIG PICTURE</p><h2>Your world awaits.</h2></div><button className="textbtn" onClick={onMap}>Explore map ↗</button></div><div className="worldCards">{ZONES.map((z,i)=><button style={{'--zone':z.color}} className={Math.floor((level.id-1)/10)===i?'worldCard selected':'worldCard'} key={z.name} onClick={onMap}><span>{z.icon}</span><small>WORLD 0{i+1}</small><b>{z.name}</b><em>{Object.keys(data.completed).filter(id=>Number(id)>i*10&&Number(id)<=(i+1)*10).length}/10 cleared</em></button>)}</div></section>
    <section className="questPanel dailyQuest"><p className="eyebrow">DAILY QUEST</p><h2>Show up. Level up.</h2><div className="questGoal"><strong>{minutes}</strong><span>/ {goal} min</span></div><progress aria-label="Daily practice minutes" value={Math.min(minutes,goal)} max={goal}/><p>{minutes>=goal?'Daily goal complete. Your consistency is paying off.':`${Math.max(0,Math.round((goal-minutes)*10)/10)} minutes left. Make them count.`}</p><button className="ghost" onClick={onCoach}>Start today’s training →</button></section></div>
    <section className="questPanel coachPreview"><span className="coachOrb">✳</span><div><p className="eyebrow">YOUR PERSONAL COACH</p><h2>{plan.title}</h2><p>{plan.reason}</p></div><button className="primary" onClick={onCoach}>Open my plan ↗</button></section>
    <section className="questPanel"><div className="questSectionTitle"><div><p className="eyebrow">EARNED, ONE KEY AT A TIME</p><h2>Your trophy shelf</h2></div><span className="muted">Milestone rewards</span></div><div className="questRewards">{[['First steps',1,'✧'],['Forest explorer',10,'♧'],['Halfway hero',25,'◇'],['Typing master',50,'♛']].map(([title,min,icon])=><div className={count>=min?'reward earned':'reward'} key={title}><span>{icon}</span><b>{title}</b><small>{count>=min?'Unlocked':`Clear ${min} level${min===1?'':'s'}`}</small></div>)}</div><div className="questThemes"><span>Journey palette</span>{[['forest','Forest',0],['ocean','Ocean',10],['sunset','Sunset',25]].map(([id,name,min])=><button aria-pressed={(data.settings.questPalette||'forest')===id} disabled={count<min} key={id} onClick={()=>onTheme(id)}>{name}{count<min?` · ${min} clears`:''}</button>)}</div></section>
  </div>;
}

export function AdventureMap({ data, onStart }) {
  const [chapter,setChapter] = useState(Math.min(4,Math.floor((data.currentLevel-1)/10)));
  const zone = ZONES[chapter];
  return <div className="adventureMap" style={{'--zone':zone.color}}><div className="questHeading"><div><p className="eyebrow">THE ADVENTURE MAP</p><h1>Every key takes<br/><em>you somewhere.</em></h1></div><span className="rankPill">{Object.keys(data.completed).length} / 50 cleared</span></div><div className="chapterTabs" aria-label="Journey worlds">{ZONES.map((z,i)=><button key={z.name} aria-pressed={chapter===i} onClick={()=>setChapter(i)}><span>{z.icon}</span> {i+1}. {z.name}</button>)}</div><section className="questMapBoard"><header><span className="mapEmblem">{zone.icon}</span><p className="eyebrow">WORLD 0{chapter+1}</p><h2>{zone.name}</h2><p>{zone.label} · Levels {chapter*10+1}–{chapter*10+10}</p></header><ol className="questPath">{LEVELS.slice(chapter*10,chapter*10+10).map((l,i)=>{const done=data.completed[l.id]; const open=l.id<=data.currentLevel; const boss=l.id%5===0;return <li key={l.id} style={{'--offset':`${[0,65,100,65,0,-65,-100,-65,0,65][i]}px`}} className={`${done?'cleared':open?'available':'sealed'} ${boss?'bossNode':''}`}><button disabled={!open} aria-label={`Level ${l.id}: ${l.title}${boss?', boss checkpoint':''}${done?`, ${done.stars} stars`:open?', available':', locked'}`} onClick={()=>onStart(l.id)}><span>{done?'✓':boss?'♛':open?l.id:'⌑'}</span></button><div className="pathCaption"><small>{boss?'BOSS CHECKPOINT':`LEVEL ${l.id}`}</small><b>{l.title}</b><span>{done?'★'.repeat(done.stars)+'☆'.repeat(3-done.stars):open?'Ready when you are':`Clear level ${l.id-1} to unlock`}</span></div></li>;})}</ol><footer>Boss checkpoints use your level’s challenge and accuracy target. Earn stars by clearing it.</footer></section></div>;
}
